### ISSUE TITLE
[Windows server 2022] Not add entry on windows firewall

### ISSUE THREAD

**Issue by dginu85** [Aldaviva/Fail2Ban4Win#37]
Hi, Not add entry on windows firewall 
![Schermata del 2024-10-14 19-51-37](https://github.com/user-attachments/assets/cf8c7346-cf60-4595-b3f7-bdb58dfc7785)
![Schermata del 2024-10-14 19-51-23](https://github.com/user-attachments/assets/42a997ad-bf31-4970-820f-9d825c916e83)

**Comment by Aldaviva** [comment]
Can you check in `configuration.json` and see if `isDryRun` is set to `true`?

**Comment by dginu85** [comment]
no

**Comment by Aldaviva** [comment]
Please refer to the [Configuration](https://github.com/Aldaviva/Fail2Ban4Win#configuration) section of the readme.

> ## Configuration

> Be aware that `isDryRun` defaults to `true` to avoid accidentally blocking traffic until you're ready.

> |Property name|Default|Description|
> |---|---|---|
> |`isDryRun`|`true`|Firewall rules will only be created or deleted when this is `false`.|

**Comment by dginu85** [comment]
Thank you, now work.
